### ISSUE TITLE
Java error when trying to run npm version

### ISSUE THREAD

**Issue by marksou** [nidi3/raml-doc#44]
I'm getting a java error when trying to run the npm run command. This is the error message that gets returned:

Problem generating RAML documentation.
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at guru.nidi.raml.doc.GeneratorConfig.getBaseOfFirstRaml(GeneratorConfig.java:82)
        at guru.nidi.raml.doc.OptionParser.parseCustomization(OptionParser.java:49
        at guru.nidi.raml.doc.OptionParser.parse(OptionParser.java:44)
        at guru.nidi.raml.doc.Main.main(Main.java:27)

**Comment by nidi3** [comment]
This is not npm specific, it's a bug when the path to the RAML does not contain a "/"
